//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_record
    {
        public int std_id { get; set; }
        public string std_name { get; set; }
        public string std_password { get; set; }
        public Nullable<int> std_ad_id { get; set; }
    
        public virtual admin_athu admin_athu { get; set; }
    }
}
